SELECT OFFER.OFFER_ID, OFFER.USER_ID, OFFER_NAME, DESCRIPTION, VENDOR_LINK, VALID_UNTIL, DISCOUNT, CREATED_AT, PHOTO_LINK, REWIEWS_RATINGS.AVG_RATING FROM profit.OFFER
LEFT JOIN (SELECT REVIEWS.OFFER_ID, AVG(REVIEWS.RATING) AVG_RATING FROM REVIEWS
	GROUP BY REVIEWS.OFFER_ID) AS REWIEWS_RATINGS
ON OFFER.OFFER_ID = REWIEWS_RATINGS.OFFER_ID
WHERE AVG_RATING > 3