SELECT OFFER_ID, OFFER.USER_ID, OFFER_NAME, DESCRIPTION, VENDOR_LINK, VALID_UNTIL, DISCOUNT, CREATED_AT, PHOTO_LINK FROM profit.OFFER 
LEFT JOIN(SELECT USERNAME, USER_ID FROM profit.user) as USER
ON OFFER.USER_ID = USER.USER_ID
WHERE USERNAME = 'Pavel1 Klapatiuk'
