SELECT USER_ID, USERNAME, Password FROM 
(SELECT USER.USER_ID,USERNAME,Password, count(USER.USER_ID) OFFER_AMOUNT FROM profit.OFFER 
LEFT JOIN profit.USER 
ON OFFER.USER_ID = USER.USER_ID
GROUP BY USER_ID) AS OFFERS_FOR_USER
WHERE OFFER_AMOUNT > 3