SELECT  USERNAME FROM 
(SELECT USERNAME, count(USER.USER_ID) OFFER_AMOUNT FROM profit.OFFER 
LEFT JOIN profit.USER 
ON OFFER.USER_ID = USER.USER_ID
WHERE DATE(OFFER.CREATED_AT) = curdate()
GROUP BY OFFER.USER_ID) AS OFFERS_FOR_USER
WHERE OFFER_AMOUNT > 1