SELECT OFFER.OFFER_ID, OFFER.USER_ID, OFFER_NAME, DESCRIPTION, VENDOR_LINK, VALID_UNTIL, DISCOUNT, CREATED_AT, PHOTO_LINK FROM profit.OFFER
LEFT JOIN (SELECT REVIEWS.OFFER_ID, count(*) AMOUNT_REVIEWS FROM REVIEWS
	GROUP BY REVIEWS.OFFER_ID) AS REWIEWS_AMOUNTS
ON OFFER.OFFER_ID = REWIEWS_AMOUNTS.OFFER_ID
WHERE AMOUNT_REVIEWS > 3